In [12]:
import pandas as pd 
import numpy as np 

univ = ['AAPL','MSFT','BAC','GS']
dates = pd.date_range('20110101','20201231')
df = pd.DataFrame(np.random.randn(len(dates),len(univ)),index=dates,columns=univ)
df

                AAPL      MSFT       BAC        GS
2011-01-01  0.032369 -0.049673  1.547544 -0.103934
2011-01-02  0.714050 -0.915305  0.317512  1.559486
2011-01-03  0.136833 -1.010697  0.201149  0.874582
2011-01-04 -0.904556 -1.257181 -0.707568 -1.495098
2011-01-05  1.221477 -1.071757 -1.740311 -0.890197
...              ...       ...       ...       ...
2020-12-27 -0.449957 -0.089591 -1.532530 -0.984829
2020-12-28 -0.379536  0.716971  1.175002 -0.528806
2020-12-29  1.388035 -0.519311  0.510776  0.554539
2020-12-30 -0.684810 -1.217683  0.937360 -1.252320
2020-12-31  0.349518 -1.436341 -1.195537 -0.298521

[3653 rows x 4 columns]

In [13]:
sector = {'AAPL':'Tech','MSFT':'Tech','BAC':'Fin','GS':'Fin'}

data = []

for dt in dates:
    for x in univ:
        data.append([x,sector[x], dt, np.random.randn(), np.random.randn()])

data = pd.DataFrame(data, columns = ['ticker','sector','date','signal1','signal2'])
data

      ticker sector       date   signal1   signal2
0       AAPL   Tech 2011-01-01  0.984731  1.177191
1       MSFT   Tech 2011-01-01 -0.108937 -0.692758
2        BAC    Fin 2011-01-01  0.184565 -0.540521
3         GS    Fin 2011-01-01 -0.663504  0.241688
4       AAPL   Tech 2011-01-02  0.080947 -1.745541
...      ...    ...        ...       ...       ...
14607     GS    Fin 2020-12-30 -0.985872  3.181471
14608   AAPL   Tech 2020-12-31 -0.850051  0.400349
14609   MSFT   Tech 2020-12-31 -1.058562 -0.628126
14610    BAC    Fin 2020-12-31 -0.615193  1.132407
14611     GS    Fin 2020-12-31 -1.239467  1.441996

[14612 rows x 5 columns]

In [14]:
data.groupby('ticker').mean(numeric_only=True)

         signal1   signal2
ticker
AAPL    0.019775  0.006376
BAC    -0.012729  0.028053
GS      0.003433  0.034380
MSFT   -0.006064  0.004756

In [15]:
data.groupby(['sector','date']).mean(numeric_only=True)

                    signal1   signal2
sector date
Fin    2011-01-01 -0.239469 -0.149416
       2011-01-02 -1.133280 -1.527887
       2011-01-03 -0.807799 -0.392815
       2011-01-04 -0.874936  1.212349
       2011-01-05 -0.754584  0.057454
...                     ...       ...
Tech   2020-12-27 -0.655077 -0.317271
       2020-12-28  1.128477 -0.602983
       2020-12-29  0.578371 -1.638765
       2020-12-30  0.599350 -0.157958
       2020-12-31 -0.954307 -0.113888

[7306 rows x 2 columns]

In [16]:
def max_minus_min(x):
    return x.max()-x.min()

data.groupby(['sector','date'])[['signal1','signal2']].apply(max_minus_min)

                    signal1   signal2
sector date
Fin    2011-01-01  0.848069  0.782210
       2011-01-02  3.434396  0.003735
       2011-01-03  0.708567  1.244901
       2011-01-04  0.666824  1.091653
       2011-01-05  1.494334  1.615853
...                     ...       ...
Tech   2020-12-27  0.458186  1.118331
       2020-12-28  0.294146  0.184111
       2020-12-29  0.812175  2.622333
       2020-12-30  1.680260  0.153481
       2020-12-31  0.208511  1.028474

[7306 rows x 2 columns]

In [17]:
def demean(x):
    return x - x.mean()

data.groupby(['sector','date'])[['signal1','signal2']].apply(demean)

                          signal1   signal2
sector date
Fin    2011-01-01 2      0.424034 -0.391105
                  3     -0.424034  0.391105
       2011-01-02 6      1.717198  0.001867
                  7     -1.717198 -0.001867
       2011-01-03 10    -0.354284  0.622450
...                           ...       ...
Tech   2020-12-29 14601 -0.406088  1.311166
       2020-12-30 14604 -0.840130 -0.076740
                  14605  0.840130  0.076740
       2020-12-31 14608  0.104255  0.514237
                  14609 -0.104255 -0.514237

[14612 rows x 2 columns]

In [18]:
df.groupby(level=0).mean()

                AAPL      MSFT       BAC        GS
2011-01-01  0.032369 -0.049673  1.547544 -0.103934
2011-01-02  0.714050 -0.915305  0.317512  1.559486
2011-01-03  0.136833 -1.010697  0.201149  0.874582
2011-01-04 -0.904556 -1.257181 -0.707568 -1.495098
2011-01-05  1.221477 -1.071757 -1.740311 -0.890197
...              ...       ...       ...       ...
2020-12-27 -0.449957 -0.089591 -1.532530 -0.984829
2020-12-28 -0.379536  0.716971  1.175002 -0.528806
2020-12-29  1.388035 -0.519311  0.510776  0.554539
2020-12-30 -0.684810 -1.217683  0.937360 -1.252320
2020-12-31  0.349518 -1.436341 -1.195537 -0.298521

[3653 rows x 4 columns]

In [19]:
month = [x.month for x in data['date']]
month

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 ...]

In [21]:
data.groupby(month).mean(numeric_only=True)

     signal1   signal2
1   0.054546  0.023416
2  -0.027876 -0.007359
3   0.030527  0.055167
4  -0.059090 -0.003158
5   0.008761  0.012692
6   0.027329  0.031530
7  -0.011507  0.044711
8   0.009049  0.012636
9   0.043694  0.025246
10 -0.078331  0.010195
11  0.021832  0.000482
12 -0.007265  0.012268

In [22]:
for key, val in data.groupby('sector'):
    print (key)

Fin
Tech

In [23]:
for key, val in data.groupby('sector'):
    print(val)

      ticker sector       date   signal1   signal2
2        BAC    Fin 2011-01-01  0.184565 -0.540521
3         GS    Fin 2011-01-01 -0.663504  0.241688
6        BAC    Fin 2011-01-02  0.583918 -1.526020
7         GS    Fin 2011-01-02 -2.850478 -1.529755
10       BAC    Fin 2011-01-03 -1.162082  0.229635
...      ...    ...        ...       ...       ...
14603     GS    Fin 2020-12-29 -1.006806 -0.782664
14606    BAC    Fin 2020-12-30  0.741386 -0.273284
14607     GS    Fin 2020-12-30 -0.985872  3.181471
14610    BAC    Fin 2020-12-31 -0.615193  1.132407
14611     GS    Fin 2020-12-31 -1.239467  1.441996

[7306 rows x 5 columns]
      ticker sector       date   signal1   signal2
0       AAPL   Tech 2011-01-01  0.984731  1.177191
1       MSFT   Tech 2011-01-01 -0.108937 -0.692758
4       AAPL   Tech 2011-01-02  0.080947 -1.745541
5       MSFT   Tech 2011-01-02 -0.939119 -1.109786
8       AAPL   Tech 2011-01-03  1.464404 -0.330911
...      ...    ...        ...       ...       ...
14601   MSFT   Tech 2020-12-29  0.172284 -0.327599
14604   AAPL   Tech 2020-12-30 -0.240779 -0.234698
14605   MSFT   Tech 2020-12-30  1.439480 -0.081217
14608   AAPL   Tech 2020-12-31 -0.850051  0.400349
14609   MSFT   Tech 2020-12-31 -1.058562 -0.628126

[7306 rows x 5 columns]

In [24]:
data

      ticker sector       date   signal1   signal2
0       AAPL   Tech 2011-01-01  0.984731  1.177191
1       MSFT   Tech 2011-01-01 -0.108937 -0.692758
2        BAC    Fin 2011-01-01  0.184565 -0.540521
3         GS    Fin 2011-01-01 -0.663504  0.241688
4       AAPL   Tech 2011-01-02  0.080947 -1.745541
...      ...    ...        ...       ...       ...
14607     GS    Fin 2020-12-30 -0.985872  3.181471
14608   AAPL   Tech 2020-12-31 -0.850051  0.400349
14609   MSFT   Tech 2020-12-31 -1.058562 -0.628126
14610    BAC    Fin 2020-12-31 -0.615193  1.132407
14611     GS    Fin 2020-12-31 -1.239467  1.441996

[14612 rows x 5 columns]

In [26]:
df1 = data.set_index(['date','ticker'])['signal1'].unstack(level=1)
df1

ticker          AAPL       BAC        GS      MSFT
date
2011-01-01  0.984731  0.184565 -0.663504 -0.108937
2011-01-02  0.080947  0.583918 -2.850478 -0.939119
2011-01-03  1.464404 -1.162082 -0.453515 -0.405540
2011-01-04  0.856637 -1.208348 -0.541523 -1.232422
2011-01-05 -1.028047 -1.501751 -0.007417 -0.185070
...              ...       ...       ...       ...
2020-12-27 -0.884171 -0.946586  0.264930 -0.425984
2020-12-28  0.981403 -0.818504  0.365713  1.275550
2020-12-29  0.984459 -0.870127 -1.006806  0.172284
2020-12-30 -0.240779  0.741386 -0.985872  1.439480
2020-12-31 -0.850051 -0.615193 -1.239467 -1.058562

[3653 rows x 4 columns]

In [27]:
df2 = data.pivot_table(index='date',columns='ticker',values='signal1')
df2

ticker          AAPL       BAC        GS      MSFT
date
2011-01-01  0.984731  0.184565 -0.663504 -0.108937
2011-01-02  0.080947  0.583918 -2.850478 -0.939119
2011-01-03  1.464404 -1.162082 -0.453515 -0.405540
2011-01-04  0.856637 -1.208348 -0.541523 -1.232422
2011-01-05 -1.028047 -1.501751 -0.007417 -0.185070
...              ...       ...       ...       ...
2020-12-27 -0.884171 -0.946586  0.264930 -0.425984
2020-12-28  0.981403 -0.818504  0.365713  1.275550
2020-12-29  0.984459 -0.870127 -1.006806  0.172284
2020-12-30 -0.240779  0.741386 -0.985872  1.439480
2020-12-31 -0.850051 -0.615193 -1.239467 -1.058562

[3653 rows x 4 columns]

In [28]:
df1.equals(df2)

True

In [29]:
data.pivot_table(index='date',columns='sector', values='signal1', aggfunc=np.mean)

C:\Users\super\AppData\Local\Temp\ipykernel_29820\3796502607.py:1: FutureWarning: The provided callable <function mean at 0x000001FFA82C3380> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  data.pivot_table(index='date',columns='sector', values='signal1', aggfunc=np.mean)

sector           Fin      Tech
date
2011-01-01 -0.239469  0.437897
2011-01-02 -1.133280 -0.429086
2011-01-03 -0.807799  0.529432
2011-01-04 -0.874936 -0.187892
2011-01-05 -0.754584 -0.606558
...              ...       ...
2020-12-27 -0.340828 -0.655077
2020-12-28 -0.226395  1.128477
2020-12-29 -0.938467  0.578371
2020-12-30 -0.122243  0.599350
2020-12-31 -0.927330 -0.954307

[3653 rows x 2 columns]

In [30]:
data.pivot_table(index='date',columns='sector', values='signal1', aggfunc=np.max)

C:\Users\super\AppData\Local\Temp\ipykernel_29820\3015779088.py:1: FutureWarning: The provided callable <function max at 0x000001FFA82C2980> is currently using DataFrameGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  data.pivot_table(index='date',columns='sector', values='signal1', aggfunc=np.max)

sector           Fin      Tech
date
2011-01-01  0.184565  0.984731
2011-01-02  0.583918  0.080947
2011-01-03 -0.453515  1.464404
2011-01-04 -0.541523  0.856637
2011-01-05 -0.007417 -0.185070
...              ...       ...
2020-12-27  0.264930 -0.425984
2020-12-28  0.365713  1.275550
2020-12-29 -0.870127  0.984459
2020-12-30  0.741386  1.439480
2020-12-31 -0.615193 -0.850051

[3653 rows x 2 columns]

In [32]:
data2=[]
for dt in dates:
    for x in ['Tech','Fin']:
        data2.append([x,dt,np.random.randn(),np.random.randn()])
        
data2 = pd.DataFrame(data2,columns=['sector','date','signal3','signal4'])
data2

     sector       date   signal3   signal4
0      Tech 2011-01-01  0.521298  0.365098
1       Fin 2011-01-01 -0.269657 -0.598946
2      Tech 2011-01-02 -0.383304  0.527615
3       Fin 2011-01-02  0.714915  0.156884
4      Tech 2011-01-03 -0.252609 -1.904585
...     ...        ...       ...       ...
7301    Fin 2020-12-29 -0.698440 -1.239746
7302   Tech 2020-12-30  1.408402 -0.046730
7303    Fin 2020-12-30 -3.046975  0.671896
7304   Tech 2020-12-31  0.490162 -2.357455
7305    Fin 2020-12-31  0.923504  0.914636

[7306 rows x 4 columns]

In [33]:
data.merge(data2,left_on=['sector','date'],right_on=['sector','date'])

      ticker sector       date   signal1   signal2   signal3   signal4
0       AAPL   Tech 2011-01-01  0.984731  1.177191  0.521298  0.365098
1       MSFT   Tech 2011-01-01 -0.108937 -0.692758  0.521298  0.365098
2        BAC    Fin 2011-01-01  0.184565 -0.540521 -0.269657 -0.598946
3         GS    Fin 2011-01-01 -0.663504  0.241688 -0.269657 -0.598946
4       AAPL   Tech 2011-01-02  0.080947 -1.745541 -0.383304  0.527615
...      ...    ...        ...       ...       ...       ...       ...
14607     GS    Fin 2020-12-30 -0.985872  3.181471 -3.046975  0.671896
14608   AAPL   Tech 2020-12-31 -0.850051  0.400349  0.490162 -2.357455
14609   MSFT   Tech 2020-12-31 -1.058562 -0.628126  0.490162 -2.357455
14610    BAC    Fin 2020-12-31 -0.615193  1.132407  0.923504  0.914636
14611     GS    Fin 2020-12-31 -1.239467  1.441996  0.923504  0.914636

[14612 rows x 7 columns]