In [1]:
import pdb

for x in ['AAPL','GS']:

    if x == 'AAPL':
        sector = 'Tech'
        tick_sz = len(x)

    elif x == 'GS':
        sector = 'Fin'
        tick_sz = len(x)

    pdb.set_trace()

> c:\users\super\appdata\local\temp\ipykernel_17680\1504966660.py(13)<module>()

ipdb>  AAPL

*** NameError: name 'AAPL' is not defined

ipdb>  GS

*** NameError: name 'GS' is not defined

ipdb>  GS

*** NameError: name 'GS' is not defined

ipdb>  c

> c:\users\super\appdata\local\temp\ipykernel_17680\1504966660.py(13)<module>()

ipdb>  c-

*** SyntaxError: invalid syntax

ipdb>  exit

In [2]:
import pandas as pd
import numpy as np

univ=['AAPL','MSFT','BAC','GS']

dates = pd.date_range('20110101','20201231')
df = pd.DataFrame(np.random.randn(len(dates), len(univ)), index=dates, columns = univ)
df

                AAPL      MSFT       BAC        GS
2011-01-01 -1.125905 -0.758463 -1.109061  0.022645
2011-01-02  1.103725 -0.110978 -1.681770 -0.181750
2011-01-03 -1.054331  0.367812  1.038646  1.052241
2011-01-04 -0.559877 -0.648880  0.564645  1.261259
2011-01-05  0.182866  0.857073  0.675989 -1.551628
...              ...       ...       ...       ...
2020-12-27 -0.268499  0.375577 -0.176447 -0.602881
2020-12-28 -1.486581 -1.470315  0.478893  0.949212
2020-12-29 -0.414605  0.282686 -0.221478 -1.387522
2020-12-30  1.118871 -0.523643  1.547274 -0.561016
2020-12-31 -1.338231 -0.228224 -0.045935 -0.293113

[3653 rows x 4 columns]

In [3]:
df.rolling(252).mean()

                AAPL      MSFT       BAC        GS
2011-01-01       NaN       NaN       NaN       NaN
2011-01-02       NaN       NaN       NaN       NaN
2011-01-03       NaN       NaN       NaN       NaN
2011-01-04       NaN       NaN       NaN       NaN
2011-01-05       NaN       NaN       NaN       NaN
...              ...       ...       ...       ...
2020-12-27  0.053860  0.046956 -0.042423  0.047003
2020-12-28  0.052152  0.042390 -0.036387  0.052283
2020-12-29  0.050325  0.043991 -0.039029  0.049534
2020-12-30  0.061651  0.041623 -0.028302  0.051453
2020-12-31  0.055574  0.039281 -0.028686  0.054870

[3653 rows x 4 columns]

In [4]:
df.rolling(252,min_periods=1).std()

                AAPL      MSFT       BAC        GS
2011-01-01       NaN       NaN       NaN       NaN
2011-01-02  1.576586  0.457841  0.404966  0.144529
2011-01-03  1.267121  0.565239  1.434184  0.661385
2011-01-04  1.039472  0.520575  1.304277  0.723689
2011-01-05  0.938329  0.682141  1.210434  1.125435
...              ...       ...       ...       ...
2020-12-27  1.093866  1.062148  0.991004  0.941182
2020-12-28  1.095940  1.066195  0.989522  0.942501
2020-12-29  1.096334  1.066252  0.989122  0.945693
2020-12-30  1.092551  1.066850  0.991616  0.943953
2020-12-31  1.096070  1.066792  0.991604  0.941125

[3653 rows x 4 columns]

In [5]:
qcut = pd.qcut(df['AAPL'], 10, labels=False)

In [6]:
qcut

2011-01-01    1
2011-01-02    8
2011-01-03    1
2011-01-04    2
2011-01-05    5
             ..
2020-12-27    3
2020-12-28    0
2020-12-29    3
2020-12-30    8
2020-12-31    0
Freq: D, Name: AAPL, Length: 3653, dtype: int64

In [7]:
qcut.value_counts().sort_index()

AAPL
0    366
1    365
2    365
3    365
4    366
5    365
6    365
7    365
8    365
9    366
Name: count, dtype: int64

In [8]:
df['AAPL'].groupby(qcut).describe()

,count,mean,std,min,25%,50%,75%,max
AAPL,,,,,,,,
0,366.0,-1.733655,0.379017,-3.473366,-1.904940,-1.638627,-1.442188,-1.303265
1,365.0,-1.056691,0.127423,-1.301329,-1.167685,-1.043490,-0.943786,-0.859214
2,365.0,-0.702491,0.093450,-0.857970,-0.786320,-0.708606,-0.619234,-0.538288
3,365.0,-0.389226,0.082093,-0.536998,-0.457766,-0.388146,-0.316966,-0.251050
4,366.0,-0.120039,0.075034,-0.251039,-0.186729,-0.117564,-0.054657,0.007891
5,365.0,0.130248,0.068767,0.008101,0.069896,0.131931,0.189250,0.245466
6,365.0,0.381910,0.080814,0.245903,0.310229,0.376497,0.451824,0.523083
7,365.0,0.686674,0.096487,0.523415,0.606909,0.682280,0.768544,0.860821
8,365.0,1.070289,0.130075,0.861275,0.971483,1.055249,1.178493,1.319867
9,366.0,1.786417,0.414191,1.320838,1.463182,1.695064,1.986233,3.383892

In [9]:
other_signal = pd.Series(np.random.randn(len(dates)), index = dates)

In [10]:
other_signal

2011-01-01   -0.941975
2011-01-02    1.123490
2011-01-03   -0.688263
2011-01-04    0.131162
2011-01-05   -0.325797
                ...
2020-12-27    1.262769
2020-12-28   -0.902830
2020-12-29    1.161323
2020-12-30   -0.875949
2020-12-31    0.200238
Freq: D, Length: 3653, dtype: float64

In [11]:
other_signal.groupby(qcut).mean()

AAPL
0   -0.029404
1   -0.047619
2    0.029592
3    0.102853
4   -0.052302
5    0.059846
6   -0.014956
7    0.019341
8   -0.031864
9   -0.046987
dtype: float64