In [2]:
import numpy as np
import pandas as pd

dt = "20110107"
dt = pd.to_datetime(dt)

In [3]:
dt

Timestamp('2011-01-07 00:00:00')

In [4]:
print(dt.year)

2011

In [5]:
print(dt.month)

1

In [6]:
print(dt.day)

7

In [7]:
print(dt.hour)

0

In [8]:
print(dt.minute)

0

In [9]:
print(dt.second)

0

In [10]:
dt.weekday()

4

In [11]:
pd.to_datetime('20110107 12:10:30')

Timestamp('2011-01-07 12:10:30')

In [12]:
dt.strftime('%Y%m%d')

'20110107'

In [13]:
dt + pd.tseries.offsets.Day()

Timestamp('2011-01-08 00:00:00')

In [14]:
dt + pd.tseries.offsets.Day(2)

Timestamp('2011-01-09 00:00:00')

In [15]:
dt + pd.tseries.offsets.BDay()

Timestamp('2011-01-10 00:00:00')

In [18]:
print(pd.tseries.offsets.MonthEnd().rollforward(dt))

2011-01-31 00:00:00

In [19]:
print(pd.tseries.offsets.MonthEnd().rollback(dt))

2010-12-31 00:00:00

In [21]:
dt1 = pd.to_datetime("20110101")

In [22]:
dt2 = pd.to_datetime("20120630")

In [23]:
diff = dt2-dt1
diff

Timedelta('546 days 00:00:00')

In [24]:
diff.days

546

In [26]:
date = ['20110102', '20110103', '20110105']

dt_index = pd.DatetimeIndex(date)
dt_index

DatetimeIndex(['2011-01-02', '2011-01-03', '2011-01-05'], dtype='datetime64[ns]', freq=None)

In [27]:
dt_index[0]

Timestamp('2011-01-02 00:00:00')

In [33]:
days = pd.date_range(dt1,dt2, freq="D")
days

DatetimeIndex(['2011-01-01', '2011-01-02', '2011-01-03', '2011-01-04',
               '2011-01-05', '2011-01-06', '2011-01-07', '2011-01-08',
               '2011-01-09', '2011-01-10',
               ...
               '2012-06-21', '2012-06-22', '2012-06-23', '2012-06-24',
               '2012-06-25', '2012-06-26', '2012-06-27', '2012-06-28',
               '2012-06-29', '2012-06-30'],
              dtype='datetime64[ns]', length=547, freq='D')

In [34]:
months = pd.date_range('20110101','20121231',freq="M")
months

C:\Users\super\AppData\Local\Temp\ipykernel_19284\996863640.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  months = pd.date_range('20110101','20121231',freq="M")

DatetimeIndex(['2011-01-31', '2011-02-28', '2011-03-31', '2011-04-30',
               '2011-05-31', '2011-06-30', '2011-07-31', '2011-08-31',
               '2011-09-30', '2011-10-31', '2011-11-30', '2011-12-31',
               '2012-01-31', '2012-02-29', '2012-03-31', '2012-04-30',
               '2012-05-31', '2012-06-30', '2012-07-31', '2012-08-31',
               '2012-09-30', '2012-10-31', '2012-11-30', '2012-12-31'],
              dtype='datetime64[ns]', freq='ME')

In [37]:
univ = ['SPY','TLT','VXX','QQQ']
days = pd.date_range('20190101','20210630',freq='min')
df = pd.DataFrame(np.random.randn(len(days),len(univ)),index=days, columns=univ)
df

                          SPY       TLT       VXX       QQQ
2019-01-01 00:00:00  0.109766 -0.294461  1.212189  0.665915
2019-01-01 00:01:00  0.881262  0.056069 -0.084243 -0.795874
2019-01-01 00:02:00  0.591742 -0.204931 -0.465073 -0.682335
2019-01-01 00:03:00  0.989109 -1.744451 -0.799017 -1.055559
2019-01-01 00:04:00 -0.009857  0.602873  0.424596 -1.444450
...                       ...       ...       ...       ...
2021-06-29 23:56:00 -1.201842  1.064816 -0.282200  0.892029
2021-06-29 23:57:00  0.665325 -1.236433  0.735449 -0.566870
2021-06-29 23:58:00  0.614627 -0.138910 -1.176616 -0.439527
2021-06-29 23:59:00  0.324939  1.141625  0.373422  0.636212
2021-06-30 00:00:00 -0.542089 -1.452936  0.598895 -1.332751

[1311841 rows x 4 columns]

In [38]:
df.loc['2019-01-01 00:00:00']

SPY    0.109766
TLT   -0.294461
VXX    1.212189
QQQ    0.665915
Name: 2019-01-01 00:00:00, dtype: float64

In [39]:
df.resample("M").sum()

C:\Users\super\AppData\Local\Temp\ipykernel_19284\1336785658.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  df.resample("M").sum()

                   SPY         TLT         VXX         QQQ
2019-01-31 -368.021883 -322.649122  103.359803    4.469193
2019-02-28  202.020358   34.014609  124.053549 -232.045713
2019-03-31 -408.076062  169.498471  106.003876 -121.036190
2019-04-30   63.539056  204.504417   95.132220  -55.277216
2019-05-31 -120.531746 -199.517248   81.361309  225.341102
2019-06-30 -224.051236   61.673768 -103.515401  222.591282
2019-07-31  102.921112   -2.593429 -277.114581 -130.680517
2019-08-31  -86.468331   28.200399  -98.169577 -183.668839
2019-09-30 -112.518195  171.661004   76.747458 -185.882385
2019-10-31  139.864691   68.760607  519.345490 -210.016487
2019-11-30 -231.810532 -147.905716 -108.906213  225.268636
2019-12-31  -55.267585 -163.397583  446.197504  188.838090
2020-01-31  282.472998  226.540424 -112.476172 -189.451848
2020-02-29 -260.552564 -114.352026 -180.514285  171.981564
2020-03-31  -81.913035 -175.123934  265.464399  132.293513
2020-04-30  553.344142  349.395731   44.847247 -267.811700
2020-05-31   54.009114 -314.680391   25.400114   19.435563
2020-06-30   35.607220 -213.152756  -69.506341 -115.164604
2020-07-31 -221.839988  202.900296  -29.437999   96.083409
2020-08-31 -192.771275  -47.197398  277.631512 -253.794249
2020-09-30  145.488198   75.769403  -11.656523 -223.240297
2020-10-31  -87.349390  -33.806411   79.675765  124.930829
2020-11-30 -143.246843  217.098019 -469.837361  -90.250578
2020-12-31 -314.601133  284.746384   21.236905 -335.167487
2021-01-31  230.099807  134.224181 -248.126233  -90.954144
2021-02-28  -22.874960  322.278553   61.774411  246.891760
2021-03-31 -224.621558  285.181211  180.273515    7.211097
2021-04-30   11.929053 -162.500322  145.597925 -145.048160
2021-05-31    0.876325  256.550636  101.181253 -204.378892
2021-06-30  131.401642  -18.760700   40.310715  -54.319900

In [40]:
df.resample("5min").max()

                          SPY       TLT       VXX       QQQ
2019-01-01 00:00:00  0.989109  0.602873  1.212189  0.665915
2019-01-01 00:05:00  0.164062  2.167463  1.064157  1.390063
2019-01-01 00:10:00  1.212246  2.792154  0.912803  1.492215
2019-01-01 00:15:00  0.844085  1.116461  0.915120  1.611310
2019-01-01 00:20:00  1.795749  0.486377  2.650055  2.236121
...                       ...       ...       ...       ...
2021-06-29 23:40:00  0.026759  0.907035  1.320122  1.467947
2021-06-29 23:45:00  0.362734  1.530939  1.615200  0.606436
2021-06-29 23:50:00  1.354264  2.298353  1.298909  1.892400
2021-06-29 23:55:00  0.665325  1.198026  0.735449  0.892029
2021-06-30 00:00:00 -0.542089 -1.452936  0.598895 -1.332751

[262369 rows x 4 columns]

In [41]:
df.resample("5min").last()

                          SPY       TLT       VXX       QQQ
2019-01-01 00:00:00 -0.009857  0.602873  0.424596 -1.444450
2019-01-01 00:05:00 -0.731272 -0.530341 -1.748417  0.808263
2019-01-01 00:10:00  1.212246 -0.475310 -0.169313  1.492215
2019-01-01 00:15:00 -0.502137  0.830999  0.020664 -0.371924
2019-01-01 00:20:00  0.164621 -0.524464 -1.675989  1.123009
...                       ...       ...       ...       ...
2021-06-29 23:40:00 -0.686011  0.634701  0.046712 -0.284106
2021-06-29 23:45:00 -1.547458  0.264892 -1.209103 -0.833470
2021-06-29 23:50:00  1.269285  2.298353 -0.602274 -0.923643
2021-06-29 23:55:00  0.324939  1.141625  0.373422  0.636212
2021-06-30 00:00:00 -0.542089 -1.452936  0.598895 -1.332751

[262369 rows x 4 columns]